// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSdpRmgCZ4iYv9jazHj4tYwkKC_0nZFpo',
    appId: '1:187126000406:web:2536781d4bfd8526c73e37',
    messagingSenderId: '187126000406',
    projectId: 'rentapp-71490',
    authDomain: 'rentapp-71490.firebaseapp.com',
    storageBucket: 'rentapp-71490.firebasestorage.app',
    measurementId: 'G-63H35GMP6J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBqTXJqbk_pwIAsw_2a8RGGRObVX5j7U4',
    appId: '1:187126000406:android:e9471e292c177a8ec73e37',
    messagingSenderId: '187126000406',
    projectId: 'rentapp-71490',
    storageBucket: 'rentapp-71490.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrW1u3Ao61h2RAXSf4JeLVVOMOt1yGrU',
    appId: '1:187126000406:ios:e69c445ee3136bfbc73e37',
    messagingSenderId: '187126000406',
    projectId: 'rentapp-71490',
    storageBucket: 'rentapp-71490.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrW1u3Ao61h2RAXSf4JeLVVOMOt1yGrU',
    appId: '1:187126000406:ios:e69c445ee3136bfbc73e37',
    messagingSenderId: '187126000406',
    projectId: 'rentapp-71490',
    storageBucket: 'rentapp-71490.firebasestorage.app',
    iosBundleId: 'com.example.rentApp',
  );
}
